name: "Deploy StrideIQ to EKS"

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI
  repository_dispatch: # Allows this pipeline to be triggered automatically via API from another repository!
    types: [deploy-app]

env:
  AWS_REGION: "us-east-1"
  CLUSTER_NAME: "eks-prod"

permissions:
  id-token: write # Required for AWS OIDC connection
  contents: read  # Required to checkout code

jobs:
  deploy:
    name: "Deploy Application"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::777311273950:role/GitHubActions-Terraform-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/strideiq-deployment.yaml
          
          # Force Kubernetes to restart the pods so it pulls the absolute newest "latest" image from DockerHub
          kubectl rollout restart deployment strideiq
